---
name: Update iCal files
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  update-ics:
    runs-on: ubuntu-latest
    permissions:
      # Required to commit/push
      contents: write
    steps:
      - name: Check out
        # zizmor: ignore[artipacked] needed for git push
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install jq
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y jq

      - name: Generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          ./cerclesdelaforme.sh > cerclesdelaforme.ics
          if [ -z "$(git status -s cerclesdelaforme.ics)" ]; then
            echo No changes to commit
            exit 0
          fi
          git config user.email "check-action@github"
          git config user.name "check-action"
          git add cerclesdelaforme.ics
          git commit -m "build(cerclesdelaforme): update iCal files"
          git push origin "${GITHUB_REF#refs/heads/}"
